### ISSUE TITLE
Discussion about moving to http-interop

### ISSUE THREAD

**Issue by harikt** [bakame-php/http-factory-slim#2]
Hi, 

I think this may be a right stuff to moved to http-interop , so we don't see many people implementing the same libraries. I would like you and @shadowhand discuss about this.

Thank you

**Comment by nyamsprod** [comment]
well this is *not the same library* just a different implementation. I'll look into it if moving it to http- interop is the right thing to do

**Comment by harikt** [comment]
@nyamsprod what made me think was looking at zend-diactoros. If you think it is not the right one. Feel free to keep it here. I haven't even discussed with @shadowhand if he is willing for the same. Just wanted both of you to discuss to know if that is possible or is right candidate.

**Comment by nyamsprod** [comment]
this repo is like https://github.com/http-interop/http-factory-diactoros
but with a different PSR-7 implementation.

**Comment by shadowhand** [comment]
FYI, `http-interop/http-factory` is available on Packagist. You will need to use `Interop\Http` instead of `Psr\Http` when importing the factory interfaces.

If you would like to transfer this package to `http-interop` we would be happy to have it. I would also add @opengeek as a contributor, as he is the FIG representative for Slim.

**Comment by nyamsprod** [comment]
While I can understand the need to move this package over the `http-interop` organization I fail to understand the added value of doing so. Having two distinct implementations made by different peoples can only make the final spec more robust IMHO. What I would rather see is an independent test suite that could validate any implementation. This is IMHO what has been missing for any previous PSR and that could be a real added value in this case.

**Comment by nyamsprod** [comment]
@harikt  @shadowhand What I'm trying to say is that I'd rather see this package being move to slimphp organization

**Comment by harikt** [comment]
@nyamsprod cool. Moving to @slimphp also works great.

**Comment by shadowhand** [comment]
@akrabat @opengeek see above. :)

**Comment by akrabat** [comment]
Looping in @silentworks and @codeguy. 

I suspect that we'll be interested when http-interop beds down some more.
